name: Build Android APK
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - 'app/**'
      - 'scripts/**'
      - '.github/workflows/**'
      - 'build.gradle'
      - 'gradle-wrapper.properties'
      - 'settings.gradle'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Download cloudflared binary
      run: |
        chmod +x ./scripts/download-cloudflared.sh
        ./scripts/download-cloudflared.sh
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
    - name: Change wrapper permissions
      run: chmod +x ./gradlew
    - name: Build APK with Gradle
      run: ./gradlew assembleDebug
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: CloudflaredApp-APK
        path: app/build/outputs/apk/debug/app-debug.apk
        retention-days: 7
